//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AuthorHTML.rc
//
#define IDM_UNKNOWN                     0
#define IDM_ALIGNBOTTOM                 1
#define IDM_CONTEXT                     1
#define IDM_ALIGNHORIZONTALCENTERS      2
#define IDM_HWND                        2
#define IDM_ALIGNLEFT                   3
#define ID_HELP_URL                     3
#define IDCANCEL2                       3
#define IDM_ALIGNRIGHT                  4
#define IDM_ALIGNTOGRID                 5
#define IDM_ALIGNTOP                    6
#define IDM_ALIGNVERTICALCENTERS        7
#define IDM_ARRANGEBOTTOM               8
#define IDM_ARRANGERIGHT                9
#define IDD_HYPERLINK                   9
#define IDM_BRINGFORWARD                10
#define IDC_HEAD_HELP                   10
#define IDM_BRINGTOFRONT                11
#define IDM_CENTERHORIZONTALLY          12
#define IDM_CENTERVERTICALLY            13
#define IDM_CODE                        14
#define IDM_COPY                        15
#define IDM_CUT                         16
#define IDM_DELETE                      17
#define IDM_FONTNAME                    18
#define IDM_FONTSIZE                    19
#define IDM_GROUP                       20
#define IDM_HORIZSPACECONCATENATE       21
#define IDM_HORIZSPACEDECREASE          22
#define IDM_HORIZSPACEINCREASE          23
#define IDM_HORIZSPACEMAKEEQUAL         24
#define IDM_INSERTOBJECT                25
#define IDM_PASTE                       26
#define IDM_PRINT                       27
#define IDM_PROPERTIES                  28
#define IDM_REDO                        29
#define IDM_MULTILEVELREDO              30
#define IDM_SELECTALL                   31
#define IDM_SENDBACKWARD                32
#define IDM_SENDTOBACK                  33
#define IDM_SHOWTABLE                   34
#define IDM_SIZETOCONTROL               35
#define IDM_SIZETOCONTROLHEIGHT         36
#define IDM_SIZETOCONTROLWIDTH          37
#define IDM_SIZETOFIT                   38
#define IDM_SIZETOGRID                  39
#define IDM_SNAPTOGRID                  40
#define IDM_TABORDER                    41
#define IDM_TOOLBOX                     42
#define IDM_UNDO                        43
#define IDM_MULTILEVELUNDO              44
#define IDM_UNGROUP                     45
#define IDM_VERTSPACECONCATENATE        46
#define IDM_VERTSPACEDECREASE           47
#define IDM_VERTSPACEINCREASE           48
#define IDM_VERTSPACEMAKEEQUAL          49
#define IDM_JUSTIFYFULL                 50
#define IDM_ZOOMPERCENT                 50
#define IDM_BACKCOLOR                   51
#define IDM_BOLD                        52
#define IDM_BORDERCOLOR                 53
#define IDM_FLAT                        54
#define IDM_FORECOLOR                   55
#define IDM_ITALIC                      56
#define IDM_JUSTIFYCENTER               57
#define IDM_JUSTIFYGENERAL              58
#define IDM_JUSTIFYLEFT                 59
#define IDM_JUSTIFYRIGHT                60
#define IDM_RAISED                      61
#define IDM_SUNKEN                      62
#define IDM_UNDERLINE                   63
#define IDM_CHISELED                    64
#define IDM_ETCHED                      65
#define IDM_SHADOWED                    66
#define IDM_FIND                        67
#define IDM_GETZOOM                     68
#define IDM_SHOWGRID                    69
#define IDM_SAVE                        70
#define IDM_SAVEAS                      71
#define IDM_OBJECTVERBLIST0             72
#define IDM_OBJECTVERBLIST1             73
#define IDM_OBJECTVERBLIST2             74
#define IDM_OBJECTVERBLIST3             75
#define IDM_OBJECTVERBLIST4             76
#define IDM_OBJECTVERBLIST5             77
#define IDM_OBJECTVERBLIST6             78
#define IDM_OBJECTVERBLIST7             79
#define IDM_OBJECTVERBLIST8             80
#define IDM_OBJECTVERBLIST9             81
#define IDM_CONVERTOBJECT               82
#define IDM_CUSTOMCONTROL               83
#define IDM_CUSTOMIZEITEM               84
#define IDM_RENAME                      85
#define IDM_IMPORT                      86
#define IDM_NEWPAGE                     87
#define IDM_MOVE                        88
#define IDM_CANCEL                      89
#define IDM_FONT                        90
#define IDM_STRIKETHROUGH               91
#define IDM_DELETEWORD                  92
#define IDM_EXECPRINT                   93
#define IDM_JUSTIFYNONE                 94
#define IDM_TRISTATEBOLD                95
#define IDM_TRISTATEITALIC              96
#define IDM_TRISTATEUNDERLINE           97
#define IDC_GRID                        99
#define IDD_ABOUTBOX                    100
#define IDD_SCINTILLA_FINDDLGORD        101
#define IDD_SCINTILLA_REPLACEDLGORD     102
#define ID_FMTBAR_FONTNAME              104
#define ID_FMTBAR_FONTSIZE              105
#define IDC_ADDRCOMBO                   106
#define IDS_STRING106                   106
#define IDR_HTML_FINDREPLACEDIALOG      107
#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 108
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 109
#define ID_VIEW_CUSTOMIZE               126
#define IDR_EXPLORER_BAR                127
#define IDR_MAINFRAME                   128
#define IDR_JAVASCRIPT                  129
#define IDR_VBSCRIPT                    130
#define IDD_URLDIALOG                   130
#define IDP_ALLOW_MODIFY_READONLY_FILE  133
#define IDR_EDITPOPUP                   136
#define IDR_TABLEBAR                    140
#define IDD_TABLE_PROPERTIES            143
#define ID_TOOLBAR_EDITING              144
#define IDD_TABPROP_PAGE1               144
#define ID_INDICATOR_VIEW               145
#define IDD_TABPROP_PAGE2               146
#define ID_FMTBAR_CLASSNAME             150
#define IDD_HR_PROPERTIES               151
#define IDD_COMMENT_DIALOG              153
#define IDD_INSERT_CHARACTER            154
#define IDD_BOOKMARKS                   155
#define IDD_DIALOG1                     156
#define IDD_DONAVIGATE                  156
#define IDD_IMAGE                       158
#define IDD_FINDREPLACE                 159
#define IDD_TOPIC_PROPERTIES            160
#define IDD_TOPIC_PROPPAGE1             161
#define IDD_TOPIC_PROPPAGE2             163
#define IDD_MARQUEE                     164
#define IDD_DIALOG2                     165
#define IDR_WORKBOOK_POPUP              166
#define IDR_EXPLORER_POPUP              167
#define IDB_BITMAP1                     168
#define IDR_HTML_POPUP                  169
#define IDR_WINDOWBAR                   170
#define IDD_STYLESHEETS                 172
#define IDD_STYLESHEET                  173
#define IDD_SS_PAGE2                    174
#define IDD_SS_PAGE1                    175
#define IDD_SS_PAGE3                    176
#define IDD_NEW_STYLERULE               178
#define IDD_SS_PAGE4                    180
#define IDD_SS_PAGE5                    181
#define IDD_SS_PAGE6                    182
#define IDD_SS_PAGE7                    183
#define IDD_PARAGRAPH                   188
#define IDD_SNAPGRID                    190
#define IDD_DIVTEXT                     192
#define IDD_FORM                        193
#define IDD_FORMFIELD                   195
#define IDD_FORMBUTTON                  197
#define IDD_TEXTAREA                    199
#define IDD_FORMIMAGE                   200
#define IDD_FORMLABEL                   202
#define IDD_FORMSELECT                  203
#define IDD_IFRAME                      204
#define IDD_GENERAL_ID                  206
#define IDD_HEADING                     207
#define IDD_SPANDIV                     209
#define IDD_SPELLING                    210
#define IDD_SPELL_OPTIONS               211
#define IDD_BUTTON                      212
#define IDD_OBJECT                      214
#define IDD_AUMESSAGEBOX                215
#define IDB_ICONASTERISK                217
#define IDB_ICONEXCLAMATION             218
#define IDB_ICONQUESTION                219
#define IDB_ICONHAND                    220
#define IDB_ALG                         221
#define IDB_ALG32                       222
#define IDB_COMPUTER                    223
#define IDB_DOCUMENTS                   224
#define IDB_INTERN1                     225
#define IDB_INTERN2                     226
#define IDB_OFFICE                      227
#define IDB_BUTTONS1                    228
#define IDB_BUTTONS2                    229
#define IDB_ARROWS                      230
#define IDB_ARROWS_WIDE                 231
#define IDB_SIGNS                       232
#define IDB_WINDOWS                     233
#define IDB_BITMAP2                     234
#define IDB_SCIENCE                     234
#define IDD_SCRIPT                      235
#define IDD_SETTINGS                    236
#define IDD_SETTINGS_PAGE1              237
#define IDD_CAPTION                     238
#define IDD_TABPROP_PAGE3               239
#define IDD_LAYER                       241
#define IDI_ICON1                       249
#define IDI_TOC_VIEW                    249
#define IDD_TAGEVENTS                   250
#define IDD_TAGEVENT                    251
#define IDC_CURSOR1                     252
#define IDD_TOPIC_PROPPAGE3             253
#define IDD_CSSIMPORTS                  254
#define IDD_AREA                        255
#define IDR_LINKBAR                     256
#define IDD_FIELDSET                    258
#define IDD_SWEEP                       259
#define IDR_PANES                       260
#define IDD_FIELDCHOOSER                261
#define IDD_FILTEREDIT                  262
#define IDB_PANEICONS                   262
#define IDB_TOC                         263
#define IDR_MENU1                       265
#define IDR_TOC_POPUP                   265
#define IDD_TOC_PROPERTIES              266
#define IDD_FIND_TOPIC                  267
#define IDR_TOC_BAR                     268
#define IDR_KEYWORD_BAR                 269
#define IDB_PROJECT                     270
#define IDB_KEYWORDS                    271
#define IDR_INDEX_POPUP                 272
#define IDD_INDEX_PROPERTIES            273
#define IDD_TOPIC_PROPPAGE4             274
#define IDD_KEYWORDS                    275
#define IDR_PROJECTBAR                  278
#define IDD_FONTSIZE                    280
#define IDD_FONT                        280
#define IDD_NEWFILE                     281
#define IDB_BITMAP3                     284
#define IDB_ALPHA_FIND                  284
#define IDR_COMPILEBAR                  285
#define IDD_COMPILE                     287
#define IDD_PROJECT                     288
#define IDD_WINDOWDEF                   289
#define IDD_WINDOWDEF_PAGE1             290
#define IDD_WINDOWDEF_PAGE2             292
#define IDD_WINDOWDEF_PAGE3             293
#define IDD_WINDOWDEF_PAGE4             294
#define IDD_AUTOSIZER                   295
#define IDD_WINDOWDEF_PAGE5             296
#define IDD_BROKENLINKS                 297
#define IDB_WRITING                     298
#define IDD_STARTUP                     299
#define IDD_IMPORT                      300
#define IDD_OPTION                      301
#define IDD_INDEX_CHOOSE                302
#define IDD_ALINK                       303
#define IDD_ALINK_COMMAND               304
#define IDD_PARAMETERS                  305
#define IDD_TOPIC_PROPPAGE5             306
#define ID_WINDOW_MANAGER               307
#define ID_VIEW_APPLOOK_WIN_2000        308
#define IDI_ICON2                       308
#define IDI_KEYWORD_VIEW                308
#define ID_VIEW_APPLOOK_OFF_XP          309
#define IDI_EXPLORER_VIEW               309
#define ID_VIEW_APPLOOK_WIN_XP          310
#define IDI_WINDOW_VIEW                 310
#define ID_VIEW_APPLOOK_OFF_2003        311
#define IDI_PROJECT_VIEW                311
#define ID_VIEW_APPLOOK_VS_2005         312
#define IDI_LINKS_VIEW                  312
#define ID_VIEW_APPLOOK_VS_2008         313
#define IDI_ICON3                       313
#define IDI_COMPILE_VIEW                313
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   314
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  315
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 316
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   317
#define ID_VIEW_APPLOOK_WINDOWS_7       318
#define IDR_POPUP_TABS                  795
#define ID_COLOR_BLUE                   797
#define ID_COLOR_YELLOW                 798
#define ID_COLOR_GREEN                  799
#define ID_COLOR_RED                    800
#define ID_COLOR_PURPLE                 801
#define ID_COLOR_CYAN                   802
#define ID_COLOR_ORANGE                 803
#define ID_COLOR_MAGENTA                804
#define ID_COLOR_NONE                   808
#define IDR_MENU_CONTEXT_GROUP          809
#define IDC_EDURL                       1000
#define IDC_FONTNAME                    1001
#define IDC_FONTSIZE                    1002
#define IDC_FONTSTYLE                   1003
#define IDC_EDIT_NUMROWS                1004
#define IDC_EDIT_NUMCOLS                1005
#define IDC_SPIN1                       1006
#define IDC_SPIN2                       1007
#define IDC_EDIT_TABLEATTRIBS           1008
#define IDC_SPIN5                       1008
#define IDC_EDIT_CELLATTRIBS            1009
#define IDC_SPIN6                       1009
#define IDC_EDIT_CAPTION                1010
#define IDC_SPIN7                       1010
#define IDC_SPIN11                      1011
#define IDC_SMINW                       1011
#define IDC_SPIN_VP                     1011
#define IDC_SPIN12                      1012
#define IDC_SMAXW                       1012
#define IDC_EXPLORER                    1013
#define IDC_SPIN14                      1013
#define IDC_SMINH                       1013
#define IDC_PHSTATIC                    1014
#define IDC_SPIN15                      1014
#define IDC_SMAXH                       1014
#define IDC_BTNGO                       1015
#define IDC_EXPLORER2                   1015
#define IDC_BTNGO2                      1016
#define IDC_BTNTGO                      1016
#define IDC_BTN_SEARCH                  1017
#define IDC_SPIN16                      1017
#define IDC_SP_R                        1017
#define IDC_BUTTON1                     1018
#define IDAPPLY                         1018
#define IDC_APPLY                       1018
#define IDC_COMMENT_HELP                1018
#define IDC_INSERT_CHAR                 1018
#define IDC_HELP_BOOKMARK               1018
#define IDC_BUTTON_OPEN                 1018
#define IDC_NAV_HELP                    1018
#define IDC_BUTTON_HELP                 1018
#define IDC_BUTTON_FILE                 1018
#define IDC_MARQUEE_HELP                1018
#define IDC_CSS_HELP                    1018
#define IDC_SS_APPLY                    1018
#define IDC_SS_COLORBUTTON              1018
#define IDC_NSR_HELP                    1018
#define IDC_BC_CHOOSE                   1018
#define IDC_BUT_LC_TOP                  1018
#define IDC_BUT_LISTIMAGE               1018
#define IDC_SPIN17                      1018
#define IDC_SP_B                        1018
#define IDC_PARA_HELP                   1018
#define IDC_GRID_HELP                   1018
#define IDC_TEXT_HELP                   1018
#define IDC_FORM_HELP                   1018
#define IDC_FF_HELP                     1018
#define IDC_FB_HELP                     1018
#define IDC_TA_HELP                     1018
#define IDC_FI_HELP                     1018
#define IDC_FL_HELP                     1018
#define IDC_FS_HELP                     1018
#define IDC_IF_HELP                     1018
#define IDC_ID_HELP                     1018
#define IDC_SPEL_IGNORE                 1018
#define IDC_SO_HELP                     1018
#define IDC_BODY_STYLE                  1018
#define IDC_OBJ_HELP                    1018
#define IDC_SCRIPT_HELP                 1018
#define IDC_BUTT_CAPTION                1018
#define IDC_LAYER_HELP                  1018
#define IDC_UP                          1018
#define IDC_FIELDSET_HELP               1018
#define IDC_FIND                        1018
#define IDC_HELP_KEYWORD                1018
#define IDC_HELP_FONTSIZE               1018
#define IDC_HELPPROJECT                 1018
#define IDC_HELPWINDOW                  1018
#define IDC_BUTTON_FILE1                1018
#define IDC_DEFAULTS                    1018
#define IDC_HELP_AUTOSIZER              1018
#define IDC_BUTTON_TOC                  1018
#define IDC_OPENPROJECT                 1018
#define IDC_SEARCH_CHM                  1018
#define IDC_DEF_SEARCH                  1018
#define IDC_BUTTON2                     1019
#define IDC_BUTTON_VIDEO                1019
#define IDC_BUTTON_TSEARCH              1019
#define IDC_BUTTON_FILE2                1019
#define IDC_OPENFILE                    1019
#define IDC_SEARCH_PRO                  1019
#define IDC_BMP_SEARCH                  1019
#define IDC_TAB1                        1020
#define IDC_TOPIC_TABS                  1020
#define IDC_WORKBOOK_TAB                1020
#define IDC_SS_TABS                     1020
#define IDC_BUTTON_LOWRES               1020
#define IDC_TAB                         1020
#define IDC_NEWPROJECT                  1020
#define IDC_CHM_SEARCH                  1020
#define IDC_NEWFILE                     1021
#define IDC_EDIT2                       1022
#define IDC_HSPACE                      1022
#define IDC_CELLNUM                     1022
#define IDC_HRWIDTH                     1022
#define IDC_ACCESKEY                    1022
#define IDC_IMG_WIDTH                   1022
#define IDC_TOPIC_FILENAME              1022
#define IDC_BODY_TOPBOTTOM              1022
#define IDC_MARQ_DELAY                  1022
#define IDB_EXPLORER_STATELIST          1022
#define IDC_CLASSNAME                   1022
#define IDC_GRID_COLOR                  1022
#define IDC_TEXT_TEXT                   1022
#define IDC_FORM_ACTION                 1022
#define IDC_FF_VALUE                    1022
#define IDC_FB_VALUE                    1022
#define IDC_TA_WIDTH                    1022
#define IDC_FI_URL                      1022
#define IDC_FS_SIZE                     1022
#define IDC_IF_SRC                      1022
#define IDC_SPEL_CORRECT                1022
#define IDC_BUTTON_VALUE                1022
#define IDC_DATA                        1022
#define IDC_SRC                         1022
#define IDC_TOC_TITLE                   1022
#define IDC_COMMENT                     1022
#define IDC_LEVEL1                      1022
#define IDC_COLOR                       1022
#define IDC_PRONAME                     1022
#define IDC_FILE1                       1022
#define IDC_INDEX                       1022
#define IDC_IMPORT                      1022
#define IDC_VALUE                       1022
#define IDC_EDIT3                       1023
#define IDC_VSPACE                      1023
#define IDC_COLHEIGHT                   1023
#define IDC_IMG_HEIGHT                  1023
#define IDC_TOPIC_TEMPLATE              1023
#define IDC_BODY_LEFTRIGHT              1023
#define IDC_REPEAT_TIMES                1023
#define IDC_RESULT_RULE                 1023
#define IDC_LW_RIGHT                    1023
#define IDC_FF_MAXLENGTH                1023
#define IDC_TA_ROWS                     1023
#define IDC_FS_NEW_OPTION               1023
#define IDC_IF_WIDTH                    1023
#define IDC_HR_COLOR                    1023
#define IDC_CODE                        1023
#define IDC_FORHTML                     1023
#define IDC_HEAD_COLS                   1023
#define IDC_LEVEL2                      1023
#define IDC_TEMPLATE                    1023
#define IDC_DEFAULTTOPIC                1023
#define IDC_FILE2                       1023
#define IDC_DEFAULT                     1023
#define IDC_TAB_HEIGHT                  1024
#define IDC_COLWIDTH                    1024
#define IDC_IMG_HPAD                    1024
#define IDC_TOPIC_AUTHOR                1024
#define IDC_TOPIC_HELP                  1024
#define IDC_IF_HEIGHT                   1024
#define IDC_EDIT24                      1024
#define IDC_FOOT_ROWS                   1024
#define IDC_ICONBITMAP                  1024
#define IDC_SPIN3                       1025
#define IDC_IMG_VPAD                    1025
#define IDC_IF_HMARGIN                  1025
#define IDC_EDIT25                      1025
#define IDC_FOOT_COLS                   1025
#define IDC_CHMFILE                     1025
#define IDC_EDIT5                       1026
#define IDC_TAB_WIDTH                   1026
#define IDC_TOPIC_COMMENT               1026
#define IDC_MARQ_HEIGHT                 1026
#define IDC_LC_TOP                      1026
#define IDC_SPIN18                      1026
#define IDC_SO_L                        1026
#define IDC_IF_VMARGIN                  1026
#define IDC_IMG_LOOP                    1026
#define IDC_CODEBASE                    1026
#define IDC_TAGNAME                     1026
#define IDC_LEVEL4                      1026
#define IDC_SPIN4                       1027
#define IDC_IF_HPAD                     1027
#define IDC_LEVEL5                      1027
#define IDC_COMBO1                      1028
#define IDC_UNITS1                      1028
#define IDC_CELLAPPLY                   1028
#define IDC_LETTER_COMBO                1028
#define IDC_FRAME_TARGET                1028
#define IDC_IMAGECOMBO                  1028
#define IDC_COMBO_FIND                  1028
#define IDC_TOPIC_STATUS                1028
#define IDC_SS_FONTWEIGHT               1028
#define IDC_NEW_SELECTOR                1028
#define IDC_BI_TILE                     1028
#define IDC_LS_TOP                      1028
#define IDC_VISIBILITY                  1028
#define IDC_PARA_ALIGN                  1028
#define IDC_FORM_METHOD                 1028
#define IDC_FF_TYPE                     1028
#define IDC_FB_TYPE                     1028
#define IDC_TA_WORDWRAP                 1028
#define IDC_FI_ALIGN                    1028
#define IDC_COMBO_WU                    1028
#define IDC_DICTIONARIES                1028
#define IDC_LANGUAGE                    1028
#define IDC_BUTTON_TYPE                 1028
#define IDC_OBJ_TYPE                    1028
#define IDC_SCRIPTTYPE                  1028
#define IDC_CAPTION_POS                 1028
#define IDC_FS_ALIGN                    1028
#define IDC_WINDOW                      1028
#define IDC_TABS                        1028
#define IDC_FACE                        1028
#define IDC_SCROLL                      1028
#define IDC_DEFWINDOW                   1028
#define IDC_WINDOWS                     1028
#define IDC_DEFAULT_TAB                 1028
#define IDC_BUTTONTYPE                  1028
#define IDC_LINKTYPE                    1028
#define IDC_COMBO2                      1029
#define IDC_UNITS2                      1029
#define IDC_TABCONTROL                  1029
#define IDC_ALIGNVERT                   1029
#define IDC_HRALIGN                     1029
#define IDC_CHAR_COMBO                  1029
#define IDC_HYPERLINK_REL               1029
#define IDC_COMBO_REPLACE               1029
#define IDC_TOPIC_PRIORITY              1029
#define IDC_SS_FONTSTYLE                1029
#define IDC_ONLY_ATTRIBUTE              1029
#define IDC_LS_LEFT                     1029
#define IDC_FLOAT                       1029
#define IDC_FORM_ENCODING               1029
#define IDC_COMBO_HU                    1029
#define IDC_IMG_VIDEO                   1029
#define IDC_CODETYPE                    1029
#define IDC_EVENT                       1029
#define IDC_SHAPE                       1029
#define IDC_LE_ALIGN                    1029
#define IDC_WINDOW_TARGET               1029
#define IDC_FRAME                       1029
#define IDC_TABPOSITION                 1029
#define IDC_MENU                        1029
#define IDC_EDIT1                       1030
#define IDC_EDITCELLIMAGE               1030
#define IDC_HRSIZE                      1030
#define IDC_EDIT_COMMENT                1030
#define IDC_EDIT_BOOKMARK               1030
#define IDC_EDIT_HYPINFO                1030
#define IDC_TOPIC_TITLE                 1030
#define IDC_BODY_BACKGROUND             1030
#define IDC_MARQ_AMOUNT                 1030
#define IDC_STYLETYPE                   1030
#define IDC_SS_TYPE                     1030
#define IDC_SELECTOR                    1030
#define IDC_SS_FONTCOLOR                1030
#define IDC_COMBO14                     1030
#define IDC_OU_T                        1030
#define IDC_ZINDEX                      1030
#define IDC_PARA_BT                     1030
#define IDC_GRID_WIDTH                  1030
#define IDC_TEXT_TITLE                  1030
#define IDC_FORM_NAME                   1030
#define IDC_FF_NAME                     1030
#define IDC_FB_NAME                     1030
#define IDC_TA_NAME                     1030
#define IDC_FI_NAME                     1030
#define IDC_FL_FOR                      1030
#define IDC_FS_NAME                     1030
#define IDC_IF_NAME                     1030
#define IDC_ID_TYPE                     1030
#define IDC_TYPE                        1030
#define IDC_SPEL_WRONG                  1030
#define IDC_BUTTON_NAME                 1030
#define IDC_NAME                        1030
#define IDC_AUMESSAGEBOX                1030
#define IDC_SCRIPT                      1030
#define IDC_CAPTION_TEXT                1030
#define IDC_LAYER_NAME                  1030
#define IDC_POLYGON                     1030
#define IDC_LEGEND                      1030
#define IDC_RELAY_TEXT                  1030
#define IDC_FILENAME                    1030
#define IDC_COMPOSITE                   1030
#define IDC_COMPILEDNAME                1030
#define IDC_LABEL1                      1030
#define IDC_TOC                         1030
#define IDC_INDENT                      1030
#define IDC_SS_INDENT                   1030
#define IDC_TEXT                        1030
#define IDC_CHM                         1030
#define IDC_TAB_NUMCOLS                 1031
#define IDC_SPIN10                      1031
#define IDC_SW                          1031
#define IDC_PARA_AT                     1031
#define IDC_GRID_HEIGHT                 1031
#define IDC_COMBO_HMU                   1031
#define IDC_ZOOM                        1031
#define IDC_LABEL2                      1031
#define IDC_SS_LETTERSPACING            1031
#define IDC_PROJECT                     1031
#define IDC_COMBO18                     1032
#define IDC_WIDTH_UNIT                  1032
#define IDC_PARA_BT2                    1032
#define IDC_PARA_INDENT                 1032
#define IDC_SNAP_WIDTH                  1032
#define IDC_COMBO_VMU                   1032
#define IDC_SPIN8                       1033
#define IDC_SPIN13                      1033
#define IDC_SH                          1033
#define IDC_PARA_SB                     1033
#define IDC_SNAP_HEIGHT                 1033
#define IDC_COMBO_HPU                   1033
#define IDC_SPIN9                       1034
#define IDC_COMBO21                     1034
#define IDC_HEIGHT_UNIT                 1034
#define IDC_PARA_SA                     1034
#define IDC_IF_VPAD                     1034
#define IDC_TAB_NUMROWS                 1035
#define IDC_SPIN19                      1035
#define IDC_SO_R                        1035
#define IDC_PARA_WS                     1035
#define IDC_COMB_VPU                    1035
#define IDC_COMBO_VPU                   1035
#define IDC_TAB_BORDER                  1036
#define IDC_SPIN20                      1036
#define IDC_SO_B                        1036
#define IDC_TAB_SPACING                 1037
#define IDC_TAB_PADDING                 1038
#define IDC_COMBO3                      1039
#define IDC_TEXTJUSTIFY                 1039
#define IDC_ALIGNHORZ                   1039
#define IDC_HYPERLINK_REV               1039
#define IDC_SS_FONTCASE                 1039
#define IDC_ONLY_PSEUDO                 1039
#define IDC_LS_RIGHT                    1039
#define IDC_POSITION                    1039
#define IDC_FORM_TARGET                 1039
#define IDC_IF_ALIGN                    1039
#define IDC_IMG_LOWRES                  1039
#define IDC_CLASSID                     1039
#define IDC_LANG                        1039
#define IDC_IMAGENUMBER                 1039
#define IDC_INDEXTYPE                   1039
#define IDC_PREVCELL                    1040
#define IDC_NEXTCELL                    1041
#define IDC_REGULAR_EXPRESSION          1042
#define IDC_CHECK1                      1042
#define IDC_CHECKHEIGHT                 1042
#define IDC_NAV_SHOWAGAIN               1042
#define IDC_KEEPRATIO                   1042
#define IDC_TODO_1                      1042
#define IDC_BODY_FIXED                  1042
#define IDC_REPEAT_CONT                 1042
#define IDC_SS_NODECOR                  1042
#define IDC_TD_NONE                     1042
#define IDC_NEW_CLASSNAME               1042
#define IDC_BI_SCROLL                   1042
#define IDC_BORDER_ALL                  1042
#define IDC_GRID_EQUAL                  1042
#define IDC_FB_CHECKED                  1042
#define IDC_FS_MULTIPLE                 1042
#define IDC_IF_NORESIZE                 1042
#define IDC_SHOWERRORS                  1042
#define IDC_DEFER                       1042
#define IDC_EDIT_LINK                   1042
#define IDC_HAS_CAPTION                 1042
#define IDC_POPUP                       1042
#define IDC_MARKASNEW                   1042
#define IDC_INTOPIC                     1042
#define IDC_CHECK2                      1043
#define IDC_CHECKWIDTH                  1043
#define IDC_CHECK_CASE                  1043
#define IDC_TODO_2                      1043
#define IDC_MARQ_ASPECT                 1043
#define IDC_TD_OVERLINE                 1043
#define IDC_USE_TOPLINE                 1043
#define IDC_SNAP_ENABLE                 1043
#define IDC_FS_NEW_DEF                  1043
#define IDC_IF_BORDER                   1043
#define IDC_IMG_BORDER                  1043
#define IDC_NUMBERIGNORE                1043
#define IDC_DCLICK_DIALOG               1043
#define IDC_HAS_HEADER                  1043
#define IDC_DO_TC                       1043
#define IDC_CHECK3                      1044
#define IDC_CHECKVERTICAL               1044
#define IDC_CHECK_WHOLE                 1044
#define IDC_TODO_3                      1044
#define IDC_MARQ_USEW                   1044
#define IDC_TD_LINETHROUGH              1044
#define IDC_USE_LEFTLINE                1044
#define IDC_SNAP_EQUAL                  1044
#define IDC_IGNORECAPITALS              1044
#define IDC_HAS_FOOTER                  1044
#define IDC_NOHREF                      1044
#define IDC_DO_BC                       1044
#define IDC_CHECK4                      1045
#define IDC_CHECKHORIZONTAL             1045
#define IDC_CHECK_UP                    1045
#define IDC_TODO_4                      1045
#define IDC_MARQ_USEH                   1045
#define IDC_SS_UNDERLINE                1045
#define IDC_TD_UNDERLINE                1045
#define IDC_USE_RIGHTLINE               1045
#define IDC_GRID_ENABLE                 1045
#define IDC_USECUSTOM                   1045
#define IDC_DO_LC                       1045
#define IDC_COMBO4                      1046
#define IDC_FORMATHEIGHT                1046
#define IDC_SS_FONTALIGN                1046
#define IDC_LS_BOTTOM                   1046
#define IDC_CLEAR                       1046
#define IDC_IF_SCROLL                   1046
#define IDC_IMG_STARTVIDEO              1046
#define IDC_ALIGN                       1046
#define IDC_BOOKMARKS                   1046
#define IDC_DO_VC                       1046
#define IDC_COMBO5                      1047
#define IDC_FORMATWIDTH                 1047
#define IDC_SS_PREDEFFONT               1047
#define IDC_OVERFLOW                    1047
#define IDC_CHECK5                      1048
#define IDC_CHECKBACKCOLOR              1048
#define IDC_CHECK_REGULAR               1048
#define IDC_TODO_5                      1048
#define IDC_SS_BLINKING                 1048
#define IDC_TD_BLINKING                 1048
#define IDC_LWU_LEFT                    1048
#define IDC_SO_ENABLE                   1048
#define IDC_DO_AC                       1048
#define IDC_AUTOSYNC                    1048
#define IDC_REFRESH                     1048
#define IDC_CLIPCHILD                   1048
#define IDC_CHECK6                      1049
#define IDC_CHECKBACKIMAGE              1049
#define IDC_TODO_6                      1049
#define IDC_LWU_RIGHT                   1049
#define IDC_DO_SCROLL                   1049
#define IDC_CHECK_COLOR                 1049
#define IDC_OPENCLOSED                  1049
#define IDC_HOME                        1049
#define IDC_CLIPSIBLINGS                1049
#define IDC_BUTT_BORDERCOLOR            1050
#define IDC_LWU_BOTTOM                  1050
#define IDC_DO_TB                       1050
#define IDC_SS_DECORATION               1050
#define IDC_CHECKBORDERCOLOR            1050
#define IDC_BUTTONBACKCOLOR             1051
#define IDC_DO_LR                       1051
#define IDC_SS_JUSTIFY                  1051
#define IDC_CHECKBORDERLIGHTCOLOR       1051
#define IDC_BACKGROUNDIMAGE             1052
#define IDC_SS_DECORATION2              1052
#define IDC_SS_WHITESPACE               1052
#define IDC_CHECKBORDERDARKCOLOR        1052
#define IDC_BUTT_DARKBORDER             1053
#define IDC_SS_WRITINGMODE              1053
#define IDC_BUTT_LIGHTBORDER            1054
#define IDC_BUTT_BGCOLORCELL            1054
#define IDC_CHOOSE_CELLIMAGE            1055
#define IDC_SPINCELLNUM                 1056
#define IDC_BUTT_BORDERCOLORCELL        1057
#define IDC_BUTT_BORDERLIGHTCOLORCELL   1058
#define IDC_HRNOSHADE                   1059
#define IDC_BUTT_BGCOLORCELL4           1059
#define IDC_BUTT_BORDERDARKCOLORCELL    1059
#define IDC_HRSHADE                     1060
#define IDC_HRCOLOR                     1062
#define IDC_RADIO_ACC_LOWER             1063
#define IDC_RADIO_ACC_UPPER             1064
#define IDC_RADIO_OTHER_UPPER           1065
#define IDC_RADIO_OHTER_LOWER           1066
#define IDC_RADIO5                      1067
#define IDC_RADIO_COMMON                1067
#define IDC_RADIO_SCROLL                1067
#define IDC_LIST1                       1068
#define IDC_LIST_BOOKMARKS              1068
#define IDC_SS_SELECTORS                1068
#define IDC_SS_DEF                      1068
#define IDC_FS_LIST                     1068
#define IDC_LIST                        1068
#define IDC_MOVETOBOOKMARK              1069
#define IDC_MOVETO_BOOKMARK             1069
#define IDC_REMOVE_BOOKMARK             1070
#define IDC_SET_BOOKMARK                1071
#define IDC_HYPERLINK_FRAME             1072
#define IDC_RADIO2                      1073
#define IDC_HYPERLINK_POPUP             1073
#define IDC_NAV_EDIT                    1073
#define IDC_RADIO_ALL                   1073
#define IDC_RADIO_RL                    1073
#define IDC_FF_PREDEF                   1073
#define IDC_NAV_NAVIGATE                1074
#define IDC_EDIT_IMGINFO                1075
#define IDC_SPIN_VPAD                   1076
#define IDC_SPIN_HPAD                   1077
#define IDC_RESET_IMAGE                 1078
#define IDC_RADIO1                      1079
#define IDC_RADIO_WHERE                 1079
#define IDC_RADIO_DOCUMENT              1079
#define IDC_RADIO_LR                    1079
#define IDC_FF_UNSPEC                   1079
#define IDC_RADIO3                      1080
#define IDC_RADIO_PROJECT               1080
#define IDC_RADIO_UP                    1080
#define IDC_FF_CUSTOM                   1080
#define IDC_RADIO4                      1081
#define IDC_RADIO_BLOCK                 1081
#define IDC_RADIO_DOWN                  1081
#define IDC_BUTTON3                     1082
#define IDC_BUTTON_REPLACEWITH          1082
#define IDC_BODY_HYPER                  1082
#define IDC_CSS_UP                      1082
#define IDC_EXT_DESCENDANT              1082
#define IDC_BUT_LC_RIGHT                1082
#define IDC_FS_NEW                      1082
#define IDC_IF_CHOOSE                   1082
#define IDC_SPEL_ADD                    1082
#define IDC_BUTT_HEADER                 1082
#define IDC_NEW                         1082
#define IDC_IMP_DELETE                  1082
#define IDC_GO                          1082
#define IDC_BUTTON_NEWPAGE              1082
#define IDC_DELWINDEF                   1082
#define IDC_BUTAPPLY                    1082
#define IDC_BUTTON4                     1083
#define IDC_BUTTON_REPLACEALL           1083
#define IDC_BODY_VISITED                1083
#define IDC_CSS_NEW                     1083
#define IDC_SS_UP                       1083
#define IDC_EXT_DIRECT                  1083
#define IDC_BUT_LC_BOTTOM               1083
#define IDC_FS_DELETE                   1083
#define IDC_STYLE                       1083
#define IDC_SPEL_CHANGE                 1083
#define IDC_BUTT_FOOTER                 1083
#define IDC_IMP_DOWN                    1083
#define IDC_BUTTON_FINDNEXT             1084
#define IDC_BUTTON6                     1084
#define IDC_BODY_ACTIVE                 1084
#define IDC_PROP_APPLY                  1086
#define IDC_TIMESPENT                   1087
#define IDC_TODO_7                      1088
#define IDC_BUTTON_TEMPLATE             1089
#define IDC_BODY_COLOR                  1092
#define IDC_BUTTON_IMAGE                1093
#define IDC_MARQUEE_APPLY               1094
#define IDC_BODY_TEXTCOLOR              1094
#define IDC_RADIO_SLIDE                 1095
#define IDC_RADIO_ALTERNATE             1096
#define IDC_EDIT4                       1097
#define IDC_MARQ_WIDTH                  1097
#define IDC_LW_BOTTOM                   1097
#define IDC_FF_SIZE                     1097
#define IDC_FS_NEW_VALUE                1097
#define IDC_IMG_BORDERWIDTH             1097
#define IDC_BASEHREF                    1097
#define IDC_LAYER_ZINDEX                1097
#define IDC_DESCRIPT                    1097
#define IDC_LEVEL3                      1097
#define IDC_DEFAULTFONT                 1097
#define IDC_FRAMETITLE                  1097
#define IDC_HELP_CHARACTER              1098
#define ID_HELP_IMAGE                   1099
#define IDC_CSS_APPLY                   1100
#define IDC_CSS_LIST                    1101
#define IDC_CSS_DELETE                  1102
#define IDC_CSS_DOWN                    1103
#define IDC_CSS_EDIT                    1104
#define IDC_SS_HELP                     1106
#define IDC_SS_NEW                      1107
#define IDC_SS_DELETE                   1108
#define IDC_SS_IMPORTS                  1109
#define IDC_SS_DOWN                     1110
#define IDC_SS_OVERLINE                 1113
#define IDC_COMBO6                      1114
#define IDC_FONTFAMILY                  1114
#define IDC_HORZ_ALIGN                  1114
#define IDC_COMBO7                      1115
#define IDC_SS_FONTSIZE                 1115
#define IDC_VERT_ALIGN                  1115
#define IDC_COMBO8                      1116
#define IDC_SS_LINEHEIGHT               1116
#define IDC_MU_L                        1116
#define IDC_PARA_LINESPACING            1116
#define IDC_FS_UNITS                    1117
#define IDC_COMBO11                     1117
#define IDC_PU_L                        1117
#define IDC_FS_UNITS2                   1118
#define IDC_LH_UNITS                    1118
#define IDC_EXT_ADJACENT                1118
#define IDC_COMBO15                     1118
#define IDC_OU_L                        1118
#define IDC_EXT_SAME                    1119
#define IDC_COMBO19                     1119
#define IDC_MINWIDTH_UNIT               1119
#define IDC_LI_UNITS                    1119
#define IDC_SLIDER1                     1120
#define IDC_COMBO22                     1120
#define IDC_MINHEIGHT_UNIT              1120
#define IDC_LS_UNITS                    1120
#define IDC_BI_CHOOSE                   1121
#define IDC_BI_TOP                      1122
#define IDC_BI_CENTER                   1123
#define IDC_BI_BOTTOM                   1124
#define IDC_RADIO6                      1125
#define IDC_LC_LEFT                     1126
#define IDC_LC_RIGHT                    1127
#define IDC_LC_BOTTOM                   1128
#define IDC_LW_TOP                      1129
#define IDC_LW_LEFT                     1130
#define IDC_LWS_TOP                     1131
#define IDC_LWS_RIGHT                   1132
#define IDC_LWS_BOTTOM                  1133
#define IDC_BUT_LC_LEFT                 1134
#define IDC_LWS_LEFT                    1135
#define IDC_BI_LEFT                     1135
#define IDC_COMBO9                      1136
#define IDC_BI_MIDDLE                   1136
#define IDC_MU_R                        1136
#define IDC_PARA_BTU                    1136
#define IDC_COMBO10                     1137
#define IDC_BI_RIGHT                    1137
#define IDC_MU_B                        1137
#define IDC_DISPLAY                     1137
#define IDC_PARA_ATU                    1137
#define IDC_BC_EDIT                     1138
#define IDC_COMBO12                     1138
#define IDC_PU_R                        1138
#define IDC_PARA_BTU2                   1138
#define IDC_PARA_INDENTU                1138
#define IDC_LWU_TOP                     1139
#define IDC_COMBO13                     1139
#define IDC_PU_B                        1139
#define IDC_PARA_SBU                    1139
#define IDC_USE_BOTTOMLINE              1140
#define IDC_COMBO16                     1140
#define IDC_OU_R                        1140
#define IDC_PARA_SAU                    1140
#define IDC_EDIT6                       1141
#define IDC_MARGIN_T                    1141
#define IDC_PARA_BTU5                   1141
#define IDC_PARA_WSU                    1141
#define IDC_ALT                         1141
#define IDC_EDIT7                       1142
#define IDC_MARGIN_L                    1142
#define IDC_ALTHTML                     1142
#define IDC_EDIT8                       1143
#define IDC_MARGIN_R                    1143
#define IDC_EDIT9                       1144
#define IDC_MARGIN_B                    1144
#define IDC_EDIT10                      1145
#define IDC_PAD_T                       1145
#define IDC_EDIT11                      1146
#define IDC_PAD_L                       1146
#define IDC_OBJ_HSPACE                  1146
#define IDC_EDIT12                      1147
#define IDC_PAD_R                       1147
#define IDC_OBJ_VSPACE                  1147
#define IDC_EDIT13                      1148
#define IDC_PAD_B                       1148
#define IDC_BORDERWIDTH                 1148
#define IDC_EDIT14                      1149
#define IDC_OFFSET_T                    1149
#define IDC_USEMAP                      1149
#define IDC_EDIT15                      1150
#define IDC_OFFSET_L                    1150
#define IDC_EDIT16                      1151
#define IDC_OFFSET_R                    1151
#define IDC_EDIT17                      1152
#define IDC_OFFSET_B                    1152
#define IDC_COMBO17                     1153
#define IDC_OU_B                        1153
#define IDC_EDIT18                      1154
#define IDC_WIDTH                       1154
#define IDC_EDIT19                      1155
#define IDC_MIN_WIDTH                   1155
#define IDC_EDIT20                      1156
#define IDC_MAX_WIDTH                   1156
#define IDC_COMBO20                     1157
#define IDC_MAXWIDTH_UNIT               1157
#define IDC_ALIGNMENT                   1157
#define IDC_EDIT22                      1158
#define IDC_MIN_HEIGHT                  1158
#define IDC_EDIT23                      1159
#define IDC_MAX_HEIGHT                  1159
#define IDC_EDIT21                      1160
#define IDC_HEIGHT                      1160
#define IDC_COMBO23                     1161
#define IDC_MAXHEIGHT_UNIT              1161
#define IDC_MU_T                        1162
#define IDC_PU_T                        1163
#define IDC_SM_T                        1164
#define IDC_SM_L                        1165
#define IDC_SM_R                        1166
#define IDC_SM_B                        1167
#define IDC_SP_T                        1168
#define IDC_SP_L                        1169
#define IDC_SO_T                        1170
#define IDC_LISTSTYLE                   1171
#define IDC_STYLEPOS                    1172
#define IDC_STYLEIMAGE                  1173
#define IDC_SPIN_Z                      1174
#define IDC_PARA_APPLY                  1175
#define IDC_SPIN_ZOOM                   1175
#define IDC_SPIN_AT                     1176
#define IDC_SPIN_BT                     1177
#define IDC_SPIN_BT2                    1178
#define IDC_SPIN_INDENT                 1178
#define IDC_GRID_BUTTCOLOR              1178
#define IDC_SPIN_SB                     1179
#define IDC_SPIN_GW                     1179
#define IDC_SPIN_SA                     1180
#define IDC_SPIN_GH                     1180
#define IDC_SPIN_WS                     1181
#define IDC_SPIN_SW                     1181
#define IDC_SPIN_SH                     1182
#define IDC_FI_CHOOSE                   1183
#define IDC_FS_DOWN                     1184
#define IDC_FS_UP                       1185
#define IDC_IF_APPLY                    1186
#define IDC_SPIN_W                      1187
#define IDC_SPIN_H                      1188
#define IDC_SPIN_HM                     1189
#define IDC_SPIN_VM                     1190
#define IDC_SPIN_HP                     1191
#define IDC_ID                          1192
#define IDC_HR_ID                       1193
#define IDC_SS_STATIC                   1194
#define IDC_BUT_STYLE                   1195
#define IDC_SPIN_BORDER                 1197
#define IDC_SD_HELP                     1198
#define IDC_SS_ATTACH                   1199
#define IDC_SPEL_SUGGEST                1200
#define IDC_BUTTON5                     1201
#define IDC_SPEL_OPTIONS                1201
#define IDC_BUTT_DATA                   1201
#define IDC_DELETE                      1201
#define IDC_DOWN                        1201
#define IDC_IMP_HELP                    1201
#define IDC_STANDBY                     1202
#define IDC_BUTT_CODE                   1203
#define IDC_CHOOSE                      1203
#define IDC_BUTT_BHREF                  1204
#define IDC_HEAD_ROWS                   1204
#define IDC_BUTT_CODEBASE               1205
#define IDC_SPIN_ZINDEX                 1205
#define IDC_SPIN_WIDTH                  1206
#define IDC_BUTT_ALTHTML                1207
#define IDC_SPIN_HEIGHT                 1207
#define IDC_BUTT_STANDBY                1208
#define IDC_BUTT_USEMAP                 1209
#define IDC_EDIT                        1209
#define IDC_EVENTS_HELP                 1210
#define IDC_EVENTS                      1211
#define IDC_IMPORTS                     1212
#define IDC_IMP_UP                      1213
#define IDC_IMP_NEW                     1214
#define IDC_GREEK_LOWER                 1215
#define IDC_GREEK_UPPER                 1216
#define IDC_STATIC1                     1217
#define IDC_STATIC2                     1218
#define IDC_STATIC3                     1219
#define IDC_STATIC4                     1220
#define IDC_TITLE                       1221
#define IDC_LEFT                        1222
#define IDC_TOP                         1223
#define IDC_RIGHT                       1224
#define IDC_BOTTOM                      1225
#define IDC_HELP_AREA                   1226
#define IDC_PROGRESS                    1227
#define IDC_DELSCRIPT                   1228
#define IDS_PROPSHT_CAPTION             1300
#define IDD_PROPPAGE_CONTROLS           1301
#define IDD_PROPPAGE_THEMES             1302
#define IDR_SKINMDTYPE                  1304
#define IDD_DIALOG_SCHEMA               1305
#define IDD_PAGE_THEME                  1306
#define IDD_PAGE_APP                    1307
#define IDD_PANE_DIALOGS                1308
#define IDB_IMAGELIST                   1309
#define IDC_LIST_THEMES                 1310
#define IDC_EDIT_NORMAL                 1311
#define IDC_COMBO_NORMAL                1312
#define IDC_COMBO_DISABLED              1313
#define IDC_LIST_SAMPLE                 1314
#define IDC_TREE_SAMPLE                 1315
#define IDC_RADIO_DEFAULT               1316
#define IDC_RADIO_LUNA                  1317
#define IDC_RADIO_OFFICE2007            1318
#define IDC_RADIO_OFFICE2000            1319
#define IDC_RADIO_OFFICEXP              1320
#define IDC_RADIO_OFFICE2003            1321
#define IDC_RADIO_WINTHEME              1322
#define IDC_RADIO_OFFICE2003_BLUE       1323
#define IDC_RADIO_OFFICE2003_OLIVE      1324
#define IDC_RADIO_OFFICE2003_METALLIC   1325
#define IDC_EDIT_SAMPLE                 1326
#define IDC_RADIO_ROYALE                1327
#define IDC_TAB_SAMPLE                  1328
#define IDC_RADIO_VISTA                 1328
#define IDC_RADIO_SKINPATH              1329
#define IDC_EDIT_DISABLED               1330
#define IDC_RADIO_SKINPATH2             1331
#define IDC_COMBO_COLORS                1332
#define IDC_COMBO_FONTS                 1333
#define IDC_CHECK_APPLYFRAME            1334
#define IDC_CHK_SELECTED                1335
#define IDC_SLIDER_NORMAL               1336
#define IDC_CHECK_APPLYMETRICS          1337
#define IDC_SLIDER_DISABLED             1338
#define IDC_BUTTON_COLORDIALOG          1339
#define IDC_CHECK_APPLYCOLORS           1340
#define IDC_BUTTON_FONTDIALOG           1341
#define IDC_BTN_DEFAULT                 1342
#define IDC_BUTTON_PRINTDIALOG          1343
#define IDC_LISTBOX_SAMPLE              1343
#define IDC_BTN_NORMAL                  1344
#define IDC_BUTTON_OPENDIALOG           1345
#define IDC_BTN_DISABLED                1346
#define IDC_RADIO_SELECTED              1347
#define IDC_RADIO_NORMAL                1348
#define IDC_RADIO_DISABLED              1349
#define IDC_CHK_NORMAL                  1350
#define IDC_CHK_DISABLED                1351
#define IDC_SCROLLBAR_NORMAL            1352
#define IDC_SCROLLBAR_DISABLED          1353
#define ID_VIEW_THEME_DIALOG            1354
#define ID_VIEW_THEME                   1355
#define IDC_BUTTON_FINDPAGE             1356
#define IDC_TOCIMAGE                    1357
#define IDC_ICONIMAGE                   1358
#define ID_HELP_FINDTOPIC               1359
#define IDC_KEYWORD                     1360
#define IDC_INFILE                      1361
#define ID_HELP_INDEXPROP               1362
#define IDC_DELINDEX                    1363
#define IDC_COLUMNLIST                  1364
#define IDC_FILTEREDIT                  1365
#define IDC_COLOR_BUTTON                1366
#define IDC_BUTTON_FSEARCH              1367
#define IDC_BTNFGO                      1368
#define ID_HELP_NEWFILE                 1369
#define IDC_NOWRAP                      1370
#define IDC_CHECK7                      1371
#define IDC_HAS_TC                      1371
#define IDC_AUTOSHOW                    1371
#define IDC_OPTIONS                     1371
#define IDC_MINBOX                      1371
#define IDC_HAS_COLOR                   1372
#define IDC_HAS_LC                      1372
#define IDC_HAS_RC                      1373
#define IDC_BUTTOTOPIC                  1373
#define IDC_HAS_LC3                     1374
#define IDC_HAS_BC                      1374
#define IDC_BUTTONFONT                  1374
#define IDC_TEXTSEARCH                  1375
#define IDC_BINARYINDEX                 1376
#define IDC_AUTOINDEX                   1377
#define IDC_NEWWINDEF                   1378
#define IDC_EDITWINDOWS                 1378
#define IDC_NAVPANE                     1379
#define IDC_FAVOURITES                  1380
#define IDC_ADVANCED                    1381
#define IDC_REMEMBER                    1382
#define IDC_GLOSSARY                    1383
#define IDC_BROWSE                      1384
#define IDC_SPIN                        1385
#define IDC_HIDESHOW                    1386
#define IDC_BACK                        1387
#define IDC_FORWARD                     1388
#define IDC_STOP                        1389
#define IDC_PRINT                       1390
#define IDC_LOCATE                      1391
#define IDC_USER1                       1392
#define IDC_USER2                       1393
#define IDC_MAXBOX                      1394
#define IDC_MAXIMIZED                   1395
#define IDC_SYSMENU                     1396
#define IDC_MINIMIZED                   1397
#define IDC_HSCROLL                     1398
#define IDC_VSCROLL                     1399
#define IDC_CHILD                       1400
#define IDC_BORDER                      1401
#define IDC_DLGFRAME                    1402
#define IDC_VISIBLE                     1403
#define IDC_OVERLAPPED                  1404
#define IDC_THICKFRAME                  1405
#define IDC_CHECK17                     1406
#define IDC_DISABLED                    1406
#define IDC_TOOL                        1407
#define IDC_CLIENTEDGE                  1408
#define IDC_STATICEDGE                  1409
#define IDC_RIGHTALIGNED                1410
#define IDC_RTL                         1411
#define IDC_CONTROLPARENT               1412
#define IDC_ACCEPTFILES                 1413
#define IDC_TOPMOST                     1414
#define IDC_CONTEXTHELP                 1415
#define IDC_NONOTIFY                    1416
#define IDC_LSCROLL                     1417
#define IDC_TRANSPARENT                 1418
#define IDC_AUTOSIZER                   1419
#define IDC_BUTTON_INDEX                1420
#define IDC_BUTTON_DEFAULT              1421
#define IDC_RESET                       1421
#define IDC_BUTTON_INDEX2               1422
#define IDC_BUTTON_HOME                 1422
#define IDC_BLINKS                      1422
#define IDC_SWEEP                       1423
#define IDC_RICHEDIT21                  1424
#define IDC_DOSWEEP                     1425
#define IDC_SELECTED                    1426
#define IDC_HELPACOMMAND                1429
#define IDC_SPINW                       1430
#define IDC_SPINH                       1431
#define IDC_PARAMETERS                  1432
#define IDC_FRAME_COLS                  1433
#define IDC_FRAME_ROWS                  1434
#define IDC_BORDER_COLOR                1435
#define IDC_FRAMEBORDER                 1436
#define IDC_FRAMESPACING                1437
#define IDM_OPEN                        2000
#define IDM_NEW                         2001
#define IDM_SAVECOPYAS                  2002
#define IDM_PRINTPREVIEW                2003
#define IDM_PAGESETUP                   2004
#define IDM_SPELL                       2005
#define IDM_PASTESPECIAL                2006
#define IDM_CLEARSELECTION              2007
#define IDM_FOLLOW_ANCHOR               2008
#define IDM_SHOWPRINT                   2010
#define IDM_SHOWPAGESETUP               2011
#define IDM_INSINPUTIMAGE               2114
#define IDM_INSINPUTBUTTON              2115
#define IDM_INSINPUTRESET               2116
#define IDM_INSINPUTSUBMIT              2117
#define IDM_INSINPUTUPLOAD              2118
#define IDM_INSFIELDSET                 2119
#define IDM_PASTEINSERT                 2120
#define IDM_REPLACE                     2121
#define IDM_EDITSOURCE                  2122
#define IDM_BOOKMARK                    2123
#define IDM_HYPERLINK                   2124
#define IDM_UNLINK                      2125
#define IDM_BROWSEMODE                  2126
#define IDM_EDITMODE                    2127
#define IDM_UNBOOKMARK                  2128
#define IDM_TOOLBARS                    2130
#define IDM_STATUSBAR                   2131
#define IDM_FORMATMARK                  2132
#define IDM_TEXTONLY                    2133
#define IDM_OPTIONS                     2135
#define IDM_FOLLOWLINKC                 2136
#define IDM_FOLLOWLINKN                 2137
#define IDM_STOP                        2138
#define IDM_VIEWSOURCE                  2139
#define IDM_ZOOMPOPUP                   2140
#define IDM_BASELINEFONT1               2141
#define IDM_BASELINEFONT2               2142
#define IDM_BASELINEFONT3               2143
#define IDM_BASELINEFONT4               2144
#define IDM_BASELINEFONT5               2145
#define IDM_HORIZONTALLINE              2150
#define IDM_LINEBREAKNORMAL             2151
#define IDM_LINEBREAKLEFT               2152
#define IDM_LINEBREAKRIGHT              2153
#define IDM_LINEBREAKBOTH               2154
#define IDM_NONBREAK                    2155
#define IDM_SPECIALCHAR                 2156
#define IDM_HTMLSOURCE                  2157
#define IDM_IFRAME                      2158
#define IDM_HTMLCONTAIN                 2159
#define IDM_TEXTBOX                     2161
#define IDM_TEXTAREA                    2162
#define IDM_CHECKBOX                    2163
#define IDM_RADIOBUTTON                 2164
#define IDM_DROPDOWNBOX                 2165
#define IDM_LISTBOX                     2166
#define IDM_BUTTON                      2167
#define IDM_IMAGE                       2168
#define IDM_OBJECT                      2169
#define IDM_1D                          2170
#define IDM_IMAGEMAP                    2171
#define IDM_FILE                        2172
#define IDM_COMMENT                     2173
#define IDM_SCRIPT                      2174
#define IDM_JAVAAPPLET                  2175
#define IDM_PLUGIN                      2176
#define IDM_PAGEBREAK                   2177
#define IDM_HTMLAREA                    2178
#define IDM_PARAGRAPH                   2180
#define IDM_FORM                        2181
#define IDM_MARQUEE                     2182
#define IDM_LIST                        2183
#define IDM_ORDERLIST                   2184
#define IDM_UNORDERLIST                 2185
#define IDM_INDENT                      2186
#define IDM_OUTDENT                     2187
#define IDM_PREFORMATTED                2188
#define IDM_ADDRESS                     2189
#define IDM_BLINK                       2190
#define IDM_DIV                         2191
#define IDM_TABLEINSERT                 2200
#define IDM_RCINSERT                    2201
#define IDM_CELLINSERT                  2202
#define IDM_CAPTIONINSERT               2203
#define IDM_CELLMERGE                   2204
#define IDM_CELLSPLIT                   2205
#define IDM_CELLSELECT                  2206
#define IDM_ROWSELECT                   2207
#define IDM_COLUMNSELECT                2208
#define IDM_TABLESELECT                 2209
#define IDM_TABLEPROPERTIES             2210
#define IDM_CELLPROPERTIES              2211
#define IDM_ROWINSERT                   2212
#define IDM_COLUMNINSERT                2213
#define IDM_HELP_CONTENT                2220
#define IDM_HELP_ABOUT                  2221
#define IDM_HELP_README                 2222
#define IDM_REMOVEFORMAT                2230
#define IDM_PAGEINFO                    2231
#define IDM_TELETYPE                    2232
#define IDM_GETBLOCKFMTS                2233
#define IDM_BLOCKFMT                    2234
#define IDM_SHOWHIDE_CODE               2235
#define IDM_TABLE                       2236
#define IDM_COPYFORMAT                  2237
#define IDM_PASTEFORMAT                 2238
#define IDM_GOTO                        2239
#define IDM_CHANGEFONT                  2240
#define IDM_CHANGEFONTSIZE              2241
#define IDM_CHANGECASE                  2246
#define IDM_SUBSCRIPT                   2247
#define IDM_SUPERSCRIPT                 2248
#define IDM_SHOWSPECIALCHAR             2249
#define IDM_CENTERALIGNPARA             2250
#define IDM_LEFTALIGNPARA               2251
#define IDM_RIGHTALIGNPARA              2252
#define IDM_REMOVEPARAFORMAT            2253
#define IDM_APPLYNORMAL                 2254
#define IDM_APPLYHEADING1               2255
#define IDM_APPLYHEADING2               2256
#define IDM_APPLYHEADING3               2257
#define IDM_DOCPROPERTIES               2260
#define IDM_ADDFAVORITES                2261
#define IDM_COPYSHORTCUT                2262
#define IDM_SAVEBACKGROUND              2263
#define IDM_SETWALLPAPER                2264
#define IDM_COPYBACKGROUND              2265
#define IDM_CREATESHORTCUT              2266
#define IDM_PAGE                        2267
#define IDM_SAVETARGET                  2268
#define IDM_SHOWPICTURE                 2269
#define IDM_SAVEPICTURE                 2270
#define IDM_DYNSRCPLAY                  2271
#define IDM_DYNSRCSTOP                  2272
#define IDM_PRINTTARGET                 2273
#define IDM_IMGARTPLAY                  2274
#define IDM_IMGARTSTOP                  2275
#define IDM_IMGARTREWIND                2276
#define IDM_PRINTQUERYJOBSPENDING       2277
#define IDM_SETDESKTOPITEM              2278
#define IDM_CONTEXTMENU                 2280
#define IDM_GOBACKWARD                  2282
#define IDM_GOFORWARD                   2283
#define IDM_PRESTOP                     2284
#define IDM_MP_MYPICS                   2287
#define IDM_MP_EMAILPICTURE             2288
#define IDM_MP_PRINTPICTURE             2289
#define IDM_CREATELINK                  2290
#define IDM_COPYCONTENT                 2291
#define IDM_LANGUAGE                    2292
#define IDM_GETPRINTTEMPLATE            2295
#define IDM_SETPRINTTEMPLATE            2296
#define IDM_TEMPLATE_PAGESETUP          2298
#define IDM_REFRESH                     2300
#define IDM_STOPDOWNLOAD                2301
#define IDM_ENABLE_INTERACTION          2302
#define IDM_LAUNCHDEBUGGER              2310
#define IDM_BREAKATNEXT                 2311
#define IDM_INSINPUTHIDDEN              2312
#define IDM_INSINPUTPASSWORD            2313
#define IDM_OVERWRITE                   2314
#define IDM_PARSECOMPLETE               2315
#define IDM_HTMLEDITMODE                2316
#define IDM_REGISTRYREFRESH             2317
#define IDM_COMPOSESETTINGS             2318
#define IDM_SHOWMISCTAGS                2320
#define IDM_SHOWALIGNEDSITETAGS         2321
#define IDM_SHOWSCRIPTTAGS              2322
#define IDM_SHOWSTYLETAGS               2323
#define IDM_SHOWCOMMENTTAGS             2324
#define IDM_SHOWAREATAGS                2325
#define IDM_SHOWUNKNOWNTAGS             2326
#define IDM_SHOWALLTAGS                 2327
#define IDM_SHOWZEROBORDERATDESIGNTIME  2328
#define IDM_AUTODETECT                  2329
#define IDM_SCRIPTDEBUGGER              2330
#define IDM_GETBYTESDOWNLOADED          2331
#define IDM_NOACTIVATENORMALOLECONTROLS 2332
#define IDM_NOACTIVATEDESIGNTIMECONTROLS 2333
#define IDM_NOACTIVATEJAVAAPPLETS       2334
#define IDM_NOFIXUPURLSONPASTE          2335
#define IDM_EMPTYGLYPHTABLE             2336
#define IDM_ADDTOGLYPHTABLE             2337
#define IDM_REMOVEFROMGLYPHTABLE        2338
#define IDM_REPLACEGLYPHCONTENTS        2339
#define IDM_SHOWWBRTAGS                 2340
#define IDM_PERSISTSTREAMSYNC           2341
#define IDM_SETDIRTY                    2342
#define IDM_RUNURLSCRIPT                2343
#define IDM_DIRLTR                      2350
#define IDM_DIRRTL                      2351
#define IDM_BLOCKDIRLTR                 2352
#define IDM_BLOCKDIRRTL                 2353
#define IDM_INLINEDIRLTR                2354
#define IDM_INLINEDIRRTL                2355
#define IDM_ISTRUSTEDDLG                2356
#define IDM_INSERTSPAN                  2357
#define IDM_LOCALIZEEDITOR              2358
#define IDM_SAVEPRETRANSFORMSOURCE      2370
#define IDM_VIEWPRETRANSFORMSOURCE      2371
#define IDM_SCROLL_HERE                 2380
#define IDM_SCROLL_TOP                  2381
#define IDM_SCROLL_BOTTOM               2382
#define IDM_SCROLL_PAGEUP               2383
#define IDM_SCROLL_PAGEDOWN             2384
#define IDM_SCROLL_UP                   2385
#define IDM_SCROLL_DOWN                 2386
#define IDM_SCROLL_LEFTEDGE             2387
#define IDM_SCROLL_RIGHTEDGE            2388
#define IDM_SCROLL_PAGELEFT             2389
#define IDM_SCROLL_PAGERIGHT            2390
#define IDM_SCROLL_LEFT                 2391
#define IDM_SCROLL_RIGHT                2392
#define IDM_MULTIPLESELECTION           2393
#define IDM_2D_POSITION                 2394
#define IDM_2D_ELEMENT                  2395
#define IDM_1D_ELEMENT                  2396
#define IDM_ABSOLUTE_POSITION           2397
#define IDM_LIVERESIZE                  2398
#define IDM_ATOMICSELECTION             2399
#define IDM_AUTOURLDETECT_MODE          2400
#define IDM_IE50_PASTE                  2401
#define IDM_IE50_PASTE_MODE             2402
#define IDM_GETIPRINT                   2403
#define IDM_DISABLE_EDITFOCUS_UI        2404
#define IDM_RESPECTVISIBILITY_INDESIGN  2405
#define IDM_CSSEDITING_LEVEL            2406
#define IDM_UI_OUTDENT                  2407
#define IDM_UPDATEPAGESTATUS            2408
#define IDM_IME_ENABLE_RECONVERSION     2409
#define IDM_KEEPSELECTION               2410
#define IDM_UNLOADDOCUMENT              2411
#define IDM_OVERRIDE_CURSOR             2420
#define IDM_PEERHITTESTSAMEINEDIT       2423
#define IDM_TRUSTAPPCACHE               2425
#define IDM_BACKGROUNDIMAGECACHE        2430
#define IDM_GETUSERACTIONTIME           2431
#define IDM_BEGINUSERACTION             2432
#define IDM_ENDUSERACTION               2433
#define IDM_SETCUSTOMCURSOR             2434
#define IDM_FOLLOWLINKT                 2435
#define IDM_MIMECSET__FIRST__           3609
#define IDM_MIMECSET__LAST__            3699
#define IDM_MENUEXT_FIRST__             3700
#define IDM_MENUEXT_LAST__              3732
#define IDM_MENUEXT_COUNT               3733
#define IDM_GETFRAMEZONE                6037
#define IDM_REFRESH_THIS                6042
#define IDM_DEFAULTBLOCK                6046
#define IDM_MENUEXT_PLACEHOLDER         6047
#define IDM_PRESERVEUNDOALWAYS          6049
#define IDM_NEW_TOPLEVELWINDOW          7050
#define IDM_PERSISTDEFAULTVALUES        7100
#define IDM_PROTECTMETATAGS             7101
#define IDM_FIRE_PRINTTEMPLATEUP        15000
#define IDM_FIRE_PRINTTEMPLATEDOWN      15001
#define IDM_SETPRINTHANDLES             15002
#define IDM_CLEARAUTHENTICATIONCACHE    15003
#define IDM_GETUSERINITFLAGS            15004
#define IDM_GETDOCDLGFLAGS              15005
#define IDM_OLEWINDOWSTATECHANGED       15006
#define IDM_SETPAGEACTIONALLOWEDFLAGS   15100
#define ID_EDIT_REPLACEAA               32708
#define ID_LANGUAGE_VBSCRIPT            32771
#define ID_OPTIONS_VIEW_LINENUMBERS     32771
#define IDC_EDIT_EDITMODE               32771
#define ID_EXPLORER_PARENT              32771
#define ID_EXPLORER_NEW                 32772
#define ID_THEME_OFFICE2000             32773
#define ID_EXPLORER_LIBRARY             32773
#define ID_THEME_OFFICEXP               32774
#define ID_FILE_OPENURL                 32774
#define ID_EXPLORER_RENAME              32774
#define ID_THEME_OFFICE2003             32775
#define IDC_EDIT_DESIGNMODE             32775
#define ID_EXPLORER_DELETE              32775
#define ID_THEME_WINXP                  32776
#define ID_EDIT_SELECTALL               32776
#define ID_EXPLORER_PROPERTIES          32776
#define ID_EDIT_FONT                    32777
#define ID_EXPLORER_SEARCH              32777
#define ID_EDIT_TEST                    32778
#define ID_OPTIONS_SELECTION_MARGIN     32779
#define ID_TABLE_INSERT                 32779
#define ID_OPTIONS_FOLD_MARGIN          32780
#define ID_TABLE_INSERTTABLE            32780
#define ID_OPTIONS_ADDMARKER            32781
#define ID_TABLE_INSERTROW              32781
#define ID_OPTIONS_DELETEMARKER         32782
#define ID_TABLE_INSERTCOLUMN           32782
#define ID_OPTIONS_FIND_NEXTMARKER      32783
#define ID_TABLE_DELETEROWS             32783
#define ID_OPTIONS_FIND_PREVMARKER      32784
#define ID_TABLE_DELETECOLUMNS          32784
#define ID_TABLE_MERGECELLS             32785
#define ID_TABLE_SPLITCELL              32786
#define ID_TABLE_INSERTCELL             32787
#define ID_TABLE_DELETECELLS            32788
#define ID_BUTTON_IMAGE                 32791
#define ID_FORMAT_SENDTOBACK            32793
#define ID_FORMAT_BRINGTOFRONT          32794
#define ID_FORMAT_SENDBACKWARD          32795
#define ID_FORMAT_BRINGFORWARD          32796
#define ID_FORMAT_SENDBELOWTEXT         32797
#define ID_FORMAT_BRINGABOVETEXT        32798
#define ID_FORMAT_ABSOLUTEPOSITIONELEMENT 32799
#define ID_FORMAT_STATICELEMENT         32800
#define ID_VIEW_WEB                     32802
#define ID_VIEW_SOURCE                  32803
#define ID_BUTTON_HYPERLINK             32804
#define ID_BUTTON_CENTERJUSTIFY         32805
#define ID_BUTTON_ABSOLUTE              32808
#define ID_BUTTONSTATIC                 32809
#define ID_BUTTON_STATIC                32809
#define ID_VIEW_TAGS                    32812
#define ID_VIEW_BROWSE                  32814
#define ID_VIEW_TABLEBORDERS            32816
#define ID_FILE_PRINTPREVIEW            32819
#define ID_BUTTON_BOLD                  32821
#define ID_BUTTON_ITALIC                32825
#define ID_BUTTON_UNDERLINE             32826
#define ID_EDIT_REPLACE_AA              32826
#define ID_BUTTON_CENTER                32827
#define ID_BUTTON_LEFTJUSTIFY           32828
#define ID_BUTTON_RIGHTJUSTIFY          32829
#define ID_BUTTON_BULLETLIST            32831
#define ID_BUTTON_OUTDENT               32832
#define ID_BUTTON_INDENT                32833
#define ID_BUTTON_NUMBERLIST            32834
#define ID_BUTTON_ANCHOR                32835
#define ID_FILE_PAGESETUP               32836
#define ID_TOGGLE_INSERT                32837
#define ID_VIEW_APPLOOK_2007            32838
#define ID_VIEW_APPLOOK_2007_1          32839
#define ID_VIEW_APPLOOK_2007_2          32840
#define ID_VIEW_APPLOOK_2007_3          32841
#define ID_VIEW_SPECIALTEST             32842
#define ID_TABLE_CELLPROPERTIES         32847
#define ID_TABLE_INSERTROWABOVE         32849
#define ID_TABLE_INSERTROWBELOW         32851
#define ID_TABLE_INSERTCOLUMNLEFT       32852
#define ID_TABLE_INSERTCOLUMNRIGHT      32853
#define ID_TABLE_DELETEROW              32854
#define ID_TABLE_DELETECOLUMN           32855
#define ID_TABLE_TABLEPROPERTIES        32856
#define ID_TABLE_COMBINECELLS           32860
#define ID_EDIT_REDO32873               32873
#define ID_BUTTON32874                  32874
#define ID_BUTTON_JUSTIFY               32875
#define ID_CONTEXTMENU_SELECTALL        32880
#define ID_CONTEXTMENU_INSERT           32883
#define ID_CONTEXTMENU_DELETEFROMTABLE  32888
#define ID_BUTTON32896                  32896
#define ID_BUTTON32897                  32897
#define ID_BUTTON_NOFORMAT              32897
#define ID_EDIT_REMOVEHYPERLINK         32898
#define ID_INSERT_BREAK                 32899
#define ID_INSERT_HORIZONTALLINE        32900
#define ID_INSERT_COMMENT               32902
#define ID_INSERT_SYMBOL                32903
#define ID_INSERT_FORM                  32904
#define ID_INSERT_FILE                  32905
#define ID_FORMAT_PARAGRAPH             32906
#define ID_EDIT_COMMENT                 32907
#define ID_CELL_TOP                     32908
#define ID_CELL_MIDDLE                  32909
#define ID_CELL_BOTTOM                  32910
#define ID_Menu32912                    32912
#define ID_BUTTON_PARAGRAPH             32915
#define ID_PROPERTIES                   32917
#define ID_MARQUEE                      32919
#define ID_INSERT_BREAKBELOWIMAGES      32920
#define ID_VIEW_WORKBOOK                32922
#define ID_EXPLORER_OPEN                32925
#define ID_EXPLORER_REFRESH             32926
#define ID_EXPLORER_GOTO_DEF_DIR        32930
#define ID_EXPLORER_SET_DEF_DIR         32932
#define ID_Menu32933                    32933
#define ID_HTMLPOPUP_FIND               32938
#define ID_HTMLPOPUP_REPLACE            32939
#define ID_Menu32940                    32940
#define ID_BUTTON_COLOR                 32945
#define ID_BUTTON_BLOCKFMT              32946
#define ID_HTMLPOPUP_DELETEFROMTABLE    32948
#define ID_WINDOW_TILEVERTICALLY        32958
#define ID_FILE_CLOSEOTHERS             32959
#define ID_CSSSTYLESHEETS               32961
#define ID_HELP_REFERENCEMANUALS        32962
#define ID_REFERENCEMANUALS_MICROSOFTHTML 32963
#define ID_REFERENCEMANUALS_W3CHTML4    32964
#define ID_REFERENCEMANUALS_W3CCSS2     32965
#define ID_HELP_HELPINDEX               32966
#define ID_HELP_RELEASENOTES            32967
#define ID_VIEW_GRID                    32969
#define ID_GRID_GRIDPROPERTIES          32972
#define ID_GRID_SHOWGRID                32973
#define ID_GRID_SNAPTOGRID              32974
#define ID_FORMAT_TEXTSTYLES            32975
#define ID_TEXTSTYLES_ABBREVIATION      32976
#define ID_TEXTSTYLES_ACRONYM           32977
#define ID_TEXTSTYLES_ADDRESS           32978
#define ID_TEXTSTYLES_BIG               32979
#define ID_TEXTSTYLES_BLOCKQUOTE        32980
#define ID_TEXTSTYLES_CITATION          32981
#define ID_TEXTSTYLES_CODE              32982
#define ID_TEXTSTYLES_DELETEDTEXT       32983
#define ID_TEXTSTYLES_INSERTEDTEXT      32984
#define ID_TEXTSTYLES_KEYBOARD          32985
#define ID_TEXTSTYLES_PREFORMATTED      32986
#define ID_TEXTSTYLES_INLINEQUOTATION   32987
#define ID_TEXTSTYLES_SAMPLE            32988
#define ID_TEXTSTYLES_SMALLER           32989
#define ID_TEXTSTYLES_SUBSCRIPT         32990
#define ID_TEXTSTYLES_SUPERSCRIPT       32991
#define ID_TEXTSTYLES_TELETYPETEXT      32992
#define ID_FORMAT_PARAGRAPHSTYLES       32993
#define ID_PARAGRAPHSTYLES_HEADING1     32995
#define ID_PARAGRAPHSTYLES_HEADING2     32996
#define ID_PARAGRAPHSTYLES_HEADING3     32997
#define ID_PARAGRAPHSTYLES_HEADING4     32998
#define ID_PARAGRAPHSTYLES_HEADING5     32999
#define ID_PARAGRAPHSTYLES_HEADING6     33000
#define ID_PARAGRAPHSTYLES_ADDRESS      33001
#define ID_PARAGRAPHSTYLES_PREFORMAT    33002
#define ID_PARAGRAPHSTYLES_PARAGRAPH    33003
#define ID_FORM_FIELD                   33004
#define ID_FORM_BUTTON                  33005
#define ID_FORM_IMAGE                   33006
#define ID_FORM_TEXTAREA                33007
#define ID_FORM_SELECTIONLIST           33008
#define ID_FORM_LABEL                   33009
#define ID_CONTEXT_FORM                 33014
#define ID_CONTEXT_FIELD                33015
#define ID_CONTEXT_TEXTAREA             33016
#define ID_FORM_FIELDSET                33017
#define ID_CONTEXT_SELECT               33020
#define ID_INSERT_IFRAME                33021
#define ID_EDIT_CHECKSPELLING           33022
#define ID_EDIT_SPELLINGOPTIONS         33025
#define ID_INSERT_BUTTON                33027
#define ID_WINDOW_MAXIMIZE              33028
#define ID_INSERT_SCRIPT                33030
#define ID_INSERT_OBJECT                33031
#define ID_TOOLS_PREFERENCES            33032
#define ID_EDIT_CAPTION                 33034
#define ID_INSERT_LAYER                 33035
#define ID_HTMLPOPUP_LAYERPROPERTIES    33036
#define ID_HTMLPOPUP_REMOVELAYER        33038
#define ID_HTMLPOPUP_ALLTAGS            33039
#define ID_ALLTAGS_FIRSTTAG             33040
#define ID_ALLTAGS_LASTTAG              33080
#define ID_BUTTON33085                  33085
#define ID_AREA_RECTANGLE               33085
#define ID_AREA_CIRCLE                  33091
#define ID_AREA_POLYGON                 33092
#define ID_HTMLPOPUP_AREAPROPERTIES     33093
#define ID_HTMLPOPUP_REMOVEAREA         33094
#define ID_PANE_TOC                     33097
#define ID_PANE_KEYWORDS                33098
#define ID_PANE_LINKS                   33099
#define ID_PANE_EXPLORER                33100
#define ID_PANE_DOCUMENTS               33101
#define ID_PANE_PROJECT                 33102
#define ID_PANE_COMPILE                 33103
#define ID_TOOLBARS_TEST                33104
#define ID_VIEW_TOOLBARSAUTO            33105
#define ID_VIEW_THEMES                  33106
#define ID_TOC_NEWBOOK                  33107
#define ID_TOC_NEWPAGE                  33108
#define ID_TOC_EDITPAGE                 33109
#define ID_TOC_MOVEUP                   33110
#define ID_TOC_MOVEDOWN                 33111
#define ID_TOC_MOVELEFT                 33112
#define ID_TOC_MOVERIGHT                33113
#define ID_TOC_RENAME                   33114
#define ID_TOC_DELETE                   33115
#define ID_TOC_BOOKFROMPAGE             33119
#define ID_TOC_FINDTOPIC                33120
#define ID_TOC_PROPERTIES               33121
#define ID_CONTEXT_MARQUEE              33122
#define ID_BUTTON33126                  33126
#define ID_SAVEALL                      33126
#define ID_TOC_PAGEFROMBOOK             33127
#define ID_KEY_NEW                      33128
#define ID_KEY_SUBKEY                   33129
#define ID_KEY_LEFT                     33130
#define ID_KEY_RIGHT                    33131
#define ID_KEY_UPPER                    33132
#define ID_BUTTON33133                  33133
#define ID_KEY_LOWER                    33134
#define ID_INDEX_NEW                    33135
#define ID_INDEX_SUBKEY                 33136
#define ID_INDEX_FINDTOPIC              33137
#define ID_INDEX_EDITPAGE               33138
#define ID_INDEX_RENAME                 33139
#define ID_INDEX_DELETE                 33140
#define ID_INDEX_MOVELEFT               33141
#define ID_INDEX_MOVERIGHT              33142
#define ID_INDEX_PROPERTIES             33143
#define ID_INDEX_FIRSTUPPER             33144
#define ID_INDEX_LOWERCASE              33145
#define ID_INDEX_EDIT                   33147
#define ID_PANE_                        33148
#define ID_WORKINGPANELS_INDEX          33149
#define ID_POPUP_COLLAPSEALLGROUPS      33150
#define ID_POPUP_EXPANDALLGROUPS        33151
#define ID_TEST_FILTERWINDOW            33152
#define ID_TEST_FIELDCHOOSER            33153
#define ID_PROJECT_NEWFILE              33154
#define ID_PROJECT_EDITFILE             33155
#define ID_PROJECT_DELETE               33156
#define ID_PROJECT_PROPERTIES           33157
#define ID_COMPILE_HELP                 33158
#define ID_CLEAR_COMPILE                33159
#define ID_CLOSE_COMPILE                33160
#define ID_READHELP                     33161
#define ID_CLOSEPROJECT                 33162
#define ID_FILE_OPENPROJECT             33163
#define ID_TOOLS_PROJECT                33164
#define IDC_WINDOWDEFS                  33165
#define ID_WINDOWDEFS                   33166
#define ID_EXPLORER_ADDTOPROJECT        33168
#define ID_FILE_NEWPROJECT              33169
#define ID_TOOLS_BROKENLINKS            33170
#define ID_STARTUP                      33171
#define ID_FILE_STARTUPDIALOG           33172
#define ID_TOOLS_IMPORTACHM             33173
#define ID_IMPORTCHM                    33174
#define ID_INSERT_ALINK                 33175
#define ID_INSERT_ALINK_COMMAND         33176
#define ID_HTML_STYLESHEETS             33177
#define ID_STYLESHEETS                  33178
#define ID_INDICATOR_LINE               61446
#define IDS_LINE_INDICATOR              61447
#define ID_INDICATOR_STYLE              61448
#define IDS_STYLE_INDICATOR             61449
#define ID_INDICATOR_FOLD               61450
#define IDS_FOLD_INDICATOR              61451
#define CMD_ZOOM_FIT                    -5
#define CMD_ZOOM_SELECTION              -4
#define CMD_ZOOM_TWOPAGES               -3
#define CMD_ZOOM_ONEPAGE                -2
#define CMD_ZOOM_PAGEWIDTH              -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         33179
#define _APS_NEXT_CONTROL_VALUE         1438
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
